### ISSUE TITLE
--contrib_s1/2 setting for constant admixture through time

### ISSUE THREAD

**Issue by sallycylau** [romain-laurent/MetHis#1]
Hi there 

I am currently playing with MetHis but I am stuck at ./generate_params.py step. In particular I am trying to build a parameter list for a scenario where the admixed population has received equal amount of admixture (0.5) from source population 1 and 2 since g=10, up until g=0. 

I have tried: 
generate_params.py -S 10 -N 10 -P ./test --Ne 1000/Con/1000-1000 --contrib_s1 default/Con/default --contrib_s2 default/Con/default

generate_params.py -S 10 -N 10 -P ./test --Ne 1000/Con/1000-1000 --contrib_s1 0.5/Con/0.5 --contrib_s2 0.5/Con/0.5

generate_params.py -S 10 -N 10 -P ./test --Ne 1000/Con/1000-1000 --contrib_s1 0.5/Con/0.5-0.5 --contrib_s2 0.5/Con/0.5-0.5

generate_params.py -S 10 -N 10 -P ./test --Ne 1000/Con/1000-1000 --contrib_s1 default/Con/0.5-0.5 --contrib_s2 default/Con/0.5-0.5

And I keep seeing this error message: "Failed parsing contrib_s1 parameter".

I wonder what have I done wrong here? Thank you! 

Best regards
Sally

**Comment by romain-laurent** [comment]
Hi Sally,

Sorry for the late answer. I just corrected the "generate_params.py" script. Now the following command works as expected :
`generate_params.py -S 10 -N 10 -P ./test --Ne 1000/Con/1000-1000 --contrib_s1 0.5/Con/0.5-0.5 --contrib_s2 0.5/Con/0.5-0.5`

Best,
Romain
